name:       isocline
version:    1.0.0         
github:     "daanx/isocline"
license:    MIT
author:     Daan Leijen
maintainer: daan@effp.org
synopsis:   A wrapper around the Isocline C library (a portable alternative to GNU Readline)
category:   console

extra-source-files:
  - readme.md  
  - haskell/readme.md
  - src/*.c
  - src/*.h
  - include/*.h

description: Please see the readme on GitHub at <https://github.com/daanx/isocline/haskell#readme>

dependencies:
  - base >= 3.0       
  - bytestring
  - text

library:
  source-dirs:
    - haskell
  c-sources:
    - src/isocline.c

executables:
  example:
    main: Example.hs
    source-dirs: test
    dependencies: 
      - isocline

tests:
  test-example:
    main: Example.hs
    source-dirs: test
    dependencies: 
      - isocline      
