#!/usr/bin/env python3
"""Generate the standalone isocline.h from the maintained library sources."""

import argparse
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "cjsh-isocline" / "src"
INCLUDE = re.compile(r'^\s*#\s*include\s+"([^"\n]+)"[^\n]*(?:\n|$)', re.MULTILINE)

BANNER = """/*
  Isocline -- single-file distribution.
  Generated by tools/amalgamate.py; edit cjsh-isocline/src/ instead.

  Copy this header into your project. In exactly one C source file, before
  including any system headers:

      #define ISOCLINE_IMPLEMENTATION
      #include "isocline.h"

  In other source files, just include "isocline.h". Compile as C11 or later;
  on POSIX systems, compile and link with -pthread. C++ callers can include
  the declarations and link against the C implementation.
*/

/* Feature macros must precede the public API's system headers. */
#if defined(ISOCLINE_IMPLEMENTATION) && !defined(ISOCLINE_IMPLEMENTATION_ONCE)
#if defined(IC_SEPARATE_OBJS)
#error "ISOCLINE_IMPLEMENTATION cannot be combined with IC_SEPARATE_OBJS"
#endif
#ifndef _CRT_NONSTDC_NO_WARNINGS
#define _CRT_NONSTDC_NO_WARNINGS
#endif
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE 700
#endif
#ifndef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE
#endif
#if defined(__APPLE__) && !defined(_DARWIN_C_SOURCE)
#define _DARWIN_C_SOURCE
#endif
#endif

"""

IMPLEMENTATION_START = """
#if defined(ISOCLINE_IMPLEMENTATION) && !defined(ISOCLINE_IMPLEMENTATION_ONCE)
#define ISOCLINE_IMPLEMENTATION_ONCE
/* Some private helpers are unused when the entire library is compiled together. */
#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
"""

IMPLEMENTATION_END = """
#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#endif
#endif /* ISOCLINE_IMPLEMENTATION */
"""


def generate():
    files = sorted(path for path in SOURCE.rglob("*") if path.suffix in (".c", ".h"))
    by_name = {}
    for path in files:
        by_name.setdefault(path.name, []).append(path)
    emitted = set()

    def resolve(parent, name):
        for candidate in (parent.parent / name, SOURCE / name):
            candidate = candidate.resolve()
            if candidate in files:
                return candidate
        candidates = by_name.get(name, [])
        if len(candidates) == 1:
            return candidates[0]
        raise ValueError(f"Cannot resolve {name!r} included by {parent.relative_to(ROOT)}")

    def expand(path):
        if path in emitted:
            return ""
        emitted.add(path)
        label = path.relative_to(SOURCE).as_posix()
        contents = INCLUDE.sub(lambda match: expand(resolve(path, match[1])),
                               path.read_text(encoding="utf-8"))
        return f"\n/* Begin {label} */\n{contents.rstrip()}\n/* End {label} */\n"

    public_api = expand(SOURCE / "isocline.h")
    implementation = expand(SOURCE / "core" / "isocline.c")
    missing = set(files) - emitted
    if missing:
        names = ", ".join(path.relative_to(SOURCE).as_posix() for path in sorted(missing))
        raise ValueError(f"Sources missing from the single-file distribution: {names}")
    return BANNER + public_api + IMPLEMENTATION_START + implementation + IMPLEMENTATION_END


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the header is out of date")
    args = parser.parse_args()
    output = ROOT / "isocline.h"
    try:
        contents = generate()
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != contents:
            print("isocline.h is out of date; run python3 tools/amalgamate.py", file=sys.stderr)
            return 1
        print("isocline.h is up to date")
    else:
        output.write_text(contents, encoding="utf-8")
        print(f"Generated isocline.h ({len(contents.splitlines()):,} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
